# fly.toml app configuration file generated for apptrack-server on 2024-01-31T00:27:14-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'apptrack-server'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8008
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
